### PR TITLE
Add Traditional Chinese (zh_tw.json)

### PR DESCRIPTION
**Pull request by dirtTW**
add Traditional Chinese localization

### CODE REVIEW

**Comment by NGoedix** [comment]
Hi, can you update the lang with the new strings?

**Comment by dirtTW** [comment]
> Hi, can you update the lang with the new strings?

Sure!, let me check

**Comment by dirtTW** [comment]
> Hi, can you update the lang with the new strings?

Done , please review it
Thank you

**Review by NGoedix — APPROVED** [review]

**Comment by NGoedix** [comment]
Will be available in the 3.0.2 in modrinth (When i finish the fabric ports to 3.0.1)

**Pull request merged**
